"""add age and check constraint to users age

Revision ID: bbcd7ea37013
Revises: 3e2ef5ebab0b
Create Date: 2024-06-07 08:36:35.869513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcd7ea37013'
down_revision = '3e2ef5ebab0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.create_check_constraint('old_enough', 'age > 12')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_constraint('ck_users_old_enough')
    # ### end Alembic commands ###
