"""add favorite_treat column

Revision ID: 5f4a80459986
Revises: 38ffcca50b33
Create Date: 2024-06-04 10:58:48.328679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4a80459986'
down_revision = '38ffcca50b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_treat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('favorite_treat')

    # ### end Alembic commands ###
