"""add nullable constraints to scientists

Revision ID: f49a58cc818c
Revises: 257cc11d1101
Create Date: 2024-06-10 10:47:56.454423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49a58cc818c'
down_revision = '257cc11d1101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scientists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scientists', 'field_of_study',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scientists', 'field_of_study',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scientists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
